# This is a basic workflow that is manually triggered

name: Manual Deploy

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  release:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Runs a single command using the runners shell
      - name: Echo version
        run: |
          RELEASE_TAG=v$(cat package.json | jq --raw-output.version)

          echo $RELEASE_TAG

          echo $RELEASE_TAG > release_tag
      - name: Push to PubSub
          run |
          RELEASE_TAG=$(cat release_tag)
          echo $RELEASE_TAG
          echo "$GCLOUD_UPLOADER_SERVICE_KEY" > service.json
          gcloud auth activate-service-account --key-file service.json
